# Robot configuration and tunable parameters

# Motor speeds
DRIVE_SPEED = 90
TURN_SPEED = 60

# Robot physical measurements
WHEEL_DIAMETER_MM = 53
AXLE_TRACK_MM = 191

# Sensors
DARK_THRESHOLD = 10

# Ultrasonic filtering
ULTRASONIC_FILTER_SAMPLES = 5
ULTRASONIC_FILTER_WAIT_MS = 5

# Timing
MAIN_LOOP_WAIT_MS = 10

# states:

# State 1- Line following
LINE_TARGET_REFLECTION = 5
LINE_KP = 0.8
MAX_LINE_CORRECTION = 80


# State 2 - Parking spot detection
SIDE_DISTANCE_GAP_THRESHOLD_MM = 250
MIN_PARALLEL_GAP_MM = 200 # 220    # 280
MIN_VERTICAL_GAP_MM = 80     # 150
GAP_DETECTION_SPEED = 100
MAX_GAP_SEARCH_DISTANCE_MM = 800
GAP_START_CONFIRMATION_COUNT = 3


# State 3 - Parking
# Parking speeds
PARKING_SPEED = 50

# Parking safety
MIN_REAR_DISTANCE_MM = 100 #80
MIN_SIDE_DISTANCE_MM = 60

# Parking correction
# PARKING_SIDE_KP = 0.6
# MAX_PARKING_CORRECTION = 40
PARKING_SIDE_KP = 0.25
MAX_PARKING_CORRECTION = 25

# Vertical parking
VERTICAL_ENTRY_FORWARD_ANGLE = 20  #80
VERTICAL_PARKING_REAR_TARGET_MM = 150
VERTICAL_ENTRY_BACKUP_ANGLE = 50


# Parallel parking
PARALLEL_ENTRY_FORWARD_ANGLE = 80
# PARALLEL_FIRST_TURN_ANGLE = 45
# PARALLEL_SECOND_TURN_ANGLE = -45
PARALLEL_FIRST_TURN_ANGLE = -25 #-30 #-23 #-45
PARALLEL_SECOND_TURN_ANGLE = 30 #23 #45
PARALLEL_FIRST_REAR_TARGET_MM = 230
PARALLEL_FINAL_REAR_TARGET_MM = 120
PARALLEL_SIDE_TARGET_MM = 120

PARALLEL_CURVE_CORRECTION = 10

PARALLEL_BACKUP_BEFORE_TURN_ANGLE = 45
PARALLEL_BACKUP_BEFORE_REVERSE_ANGLE = 95 #140


# Parking movement limits
MAX_VERTICAL_REVERSE_ANGLE = 700
MAX_PARALLEL_FIRST_REVERSE_ANGLE = 250 #450# 1100 #900 #700 #500
MAX_PARALLEL_FINAL_REVERSE_ANGLE = 500
MAX_FORWARD_ENTRY_ANGLE = 250